### PR TITLE
Removed redundant files from old documentation and expanded the main README.md file.

### PR DESCRIPTION
**Pull request by jackieh**
The additional files, additional directory, and lack of pointers in the main README.md file created confusion when searching for the relevant documentation, so hopefully the nature of this project will be more straightforward to someone glancing at this repository.

### CODE REVIEW

**Comment by davidgarland** [comment]
Besides some inconsistencies with capitalization on headers (which can be fixed in a future PR), I think it looks good. Approved, on my end.

**Comment by jorolf** [comment]
I'm not sure wether the readme should mention the c++ compiler considering that were going to replace it with the kotlin one

**Comment by jorolf** [comment]
And could you update docs/readme.md and the other files with headers and links etc.

**Comment by jackieh** [comment]
The internal links at the top of `*.md` files have been fixed. I would very much prefer to not change anything about the choice of language implementing the first compiler (between C++ and Kotlin) in this pull request because it looks like there's no consensus regarding this yet in the Discord and I'm not the one who has any final say in this decision. It seems more appropriate for someone else to make that change in a subsequent pull request.

**Pull request merged**
